### ISSUE TITLE
Add 'how to use mobile-drag-drop' as polyfill to README

### ISSUE THREAD

**Issue by penghuili** [reppners/ngx-drag-drop#10]
Thanks for the great lib!
It will be even better to add a section in Readme about how to use mobile-drag-drop as polyfills. I spent quite some time to find out that i need to firstly `yarn add mobile-drag-drop` myself and add this code to `polyfills.ts`:

```
import { polyfill } from 'mobile-drag-drop';
// optional import of scroll behaviour
import { scrollBehaviourDragImageTranslateOverride } from "mobile-drag-drop/scroll-behaviour";
polyfill( {
  // use this to make use of the scroll behaviour
  dragImageTranslateOverride: scrollBehaviourDragImageTranslateOverride
} );
window.addEventListener( "touchmove", function() {
  // workaround to make scroll prevent work in iOS Safari > 10
} );
```

**Comment by reppners** [comment]
Thanks for your feedback! 

#9 describes the same issue. I'll add a brief section with content like you suggested.

**Comment by reppners** [comment]
Updated the readme with your instructions, thanks!
