### ISSUE TITLE
Drag image that isn't part of the draggable

### ISSUE THREAD

**Issue by alberthaff** [reppners/ngx-drag-drop#110]
**Is your feature request related to a problem? Please describe.**
I'm having trouble showing an image as the dndDragImageRef, without having it visible when the user isn't dragging the draggable.

**Describe the solution you'd like**
It would be nice to be able to add a dndDragImageRef without having the element be visible by default.
The dndDragImageRef should only be visible when the user is actively dragging the given draggable.

**Describe alternatives you've considered**
I've tried hiding the dndDragImageRef with css until a drag is started, but it doesn't work all the time. 
Sometimes, part of the surrounding HTML will be used as the dndDragImageRef - so my workaround isn't stable enough.

**Comment by ChristofFritz** [comment]
That's a Browser limitation sadly. 

> Note: If the [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) is an existing [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) it needs to be visible in the viewport in order to be shown as a drag feedback image. Alternatively, you can create a new DOM element that might be off-screen specifically for this purpose.

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage
