### ISSUE TITLE
Question - Is it possible to cancel/revert after a dropping an item

### ISSUE THREAD

**Issue by vonAnden** [reppners/ngx-drag-drop#114]
Hi

Is it possible to ask the user to confirm the drag and drop after the user have dragged an item. Can I revert/cancel the drag and drop?

And if possible, how to do it?. Can the events dndMoved or dndEnd be used to trigger a dialog and if so, how to cancel the drag and drop it the user says no?

**Comment by reppners** [comment]
Since your application logic decides what should happen after the drop you may handle this as a successful drop as far as this library is concerned but conditionally fulfill the action you intend after your dialog result is available.

**Comment by vonAnden** [comment]
Thank you.

**Comment by kiran-pathe** [comment]
@reppners  Can you provide a demo link how to cancel drop ?
I am looking for an example where I can see an error toast in case of invalid drop and for successful drop, it should moved to dropzone.
