### ISSUE TITLE
How to show empty placeholder

### ISSUE THREAD

**Issue by sandeepsuvit** [reppners/ngx-drag-drop#116]
In my application i would like to display an empty text or placeholder image when the list inside the dropzone is empty. Is there a directive i can use to achieve this?

**Comment by reppners** [comment]
This can be done by what angular provides e.g. with an *ngIf inside your dropzone. The emptiness of the dropzone should be determined by your application code.

**Comment by ChristofFritz** [comment]
@sandeepsuvit you'll find an example in the demo application [here](https://github.com/reppners/ngx-drag-drop/blob/master/projects/demo/src/app/list/list.component.html#L13)
