### ISSUE TITLE
Update to Angular v15

### ISSUE THREAD

**Issue by ChristofFritz** [reppners/ngx-drag-drop#128]

**Comment by ChristofFritz** [comment]
Please.

**Comment by reppners** [comment]
That would be very much appreciated! Sent out an invite. For publishing to npm you'd need an npm user account. If you have one please send me your username there so I can invite you there, too.

**Comment by ChristofFritz** [comment]
My username on npm is nxtman

**Comment by ChristofFritz** [comment]
Version 15 is out. For now only as pre-release until I validated everything still works. 
To install, run: `npm i ngx-drag-drop@next`
