### ISSUE TITLE
Placeholder doesn't disappear when working with multiple dropzones

### ISSUE THREAD

**Issue by matheusdavidson** [reppners/ngx-drag-drop#132]
**Describe the bug**
I'm working with a list of panels, inside each panel I have the drag and drop functionality on a list like this:
-- Panel 1 (drop)
---- item 1 (drag)
---- item 2 (drag)

-- Panel 2 (drop)
---- item 1 (drag)
---- item 2 (drag)

It works fine and I can move between them but the placeholder won't disappear if I drag an item from a panel to the other, It stays fixed on the source dropzone and a new placeholder appears on the other dropzone. 

I have made a demo to reproduce:
https://stackblitz.com/edit/angular-uhhcf3?file=src/app/app.component.html

**To Reproduce**
demo: https://stackblitz.com/edit/angular-uhhcf3?file=src/app/app.component.html

1. Go to the demo
2. Drag an item from one panel(dropzone) to the other, make sure to drag it slowly, if you drag it quick it works fine.
3. See error

**Expected behavior**
The placeholder should be visible only on the dropzone it's being dragged over

**Screenshots**
![Screenshot 2022-12-31 at 00 14 12](https://user-images.githubusercontent.com/2229994/210123347-d04df38d-f08c-4f55-aea0-abc05c804f20.png)
![image](https://user-images.githubusercontent.com/2229994/210123449-1e3e1512-e222-4301-884d-530ca830d7c2.png)

**Desktop (please complete the following information):**
 - Browser: Chrome/108.0.5359.124
 - Angular v15
 - ngx-drag-drop v15.0.1

**Additional context**
Congrats for the great work!

**Comment by ChristofFritz** [comment]
Sorry that it took so long, but it should be fixed now.
