### ISSUE TITLE
Placeholder doesn't disappear when working with multiple dropzones. Part 2

### ISSUE THREAD

**Issue by AlexanderFSP** [reppners/ngx-drag-drop#145]
**Describe the bug**

Same as https://github.com/reppners/ngx-drag-drop/issues/132, the problem still relevant for @angular/core@16 and ngx-drag-drop@16.

**To Reproduce**
https://stackblitz.com/edit/stackblitz-starters-fixgve

1. Go to the demo
2. Drag an item from one panel(dropzone) to the other, **make sure to drag it slowly**, if you drag it quick it works fine.
3. See error

**Expected behavior**
The placeholder should be visible only on the dropzone it's being dragged over

**Desktop (please complete the following information):**
- Browser: Chrome/113.0.5672.126
- Angular v16
- ngx-drag-drop v16.0.0

**Comment by AlexanderFSP** [comment]
The problem actually here (https://github.com/reppners/ngx-drag-drop/blob/master/projects/dnd/src/lib/dnd-dropzone.directive.ts#LL260C1-L260C1), as I understand. When user slowly moves out draggable element - `dragleave` event fires and `document.elementFromPoint(event.clientX, event.clientY)` returns the current drop zone element. Which evaluates to true in if statement, so placeholder stays in the DOM.

**Comment by AlexanderFSP** [comment]
```
const newTarget = (event as unknown as { relatedTarget: Element }).relatedTarget;
```

instead of 

```
const newTarget = document.elementFromPoint(event.clientX, event.clientY);
```

Solved problem for me. I'll research this staff a little and open PR, when I'll be free.

**Comment by Padamdam** [comment]
Any news on this ?

**Comment by lavaloop-official** [comment]
I think that fix would be great.

**Comment by ChristofFritz** [comment]
Sory for the long wait folks. Life has been busy lately.
