### ISSUE TITLE
Question using Drag&Drop in a Tree

### ISSUE THREAD

**Issue by mrmscmike** [reppners/ngx-drag-drop#147]
I am currently working on implementing the ngx-drag-drop library within a simple tree structure. While I have made progress with moving nodes around, I have encountered an issue specifically related to adding a node as a child of another node that does not have any children yet.

Here's the breakdown of the functionality that is currently working fine:
- Moving a node within its parent's children (changing the index of a node) functions correctly.
- Changing a nodes parent.
- Moving a node to the end of the list, making it the last sibling, works as expected.
- Moving a node to the end of the list, placing it as the next sibling of its parent, functions correctly, albeit with some difficulty. Determining whether a node should be placed as the last sibling or as a sibling of its parent requires dragging the node and moving it left or right. While a placeholder is displayed to indicate the outcome upon dropping the node, it is not so easy to get what you want.

![Determining whether a node should be placed as the last sibling or as a sibling of its parent ](https://github.com/reppners/ngx-drag-drop/assets/38938465/30c3f12b-42b5-4012-af27-f77c22075f8e)

However, I am facing challenges when attempting to add a node as a child of a node that currently does not contain any children. I am able to solve it without ngx-drag-drop, but I wonder if I am missing something.

I would greatly appreciate any guidance or suggestions on how to enable the functionality of adding a node as a child of a node without existing children and how to improve the behavior when moving a node to the end of the list, determining whether a node should be placed as the last sibling or as a sibling of its parent.

I have created a [stackblitz](https://stackblitz.com/edit/angular-draggable-mat-tree-cu2tmi?file=src%2Fapp%2Fapp.component.ts)

Thanks in advance

**Comment by ChristofFritz** [comment]
I have an Idea on how to solve this. I'll try to build a demo page for you.

**Comment by ChristofFritz** [comment]
I built a demo. Take a look here:

https://reppners.github.io/ngx-drag-drop/tree

and here:

https://github.com/reppners/ngx-drag-drop/tree/master/projects/demo/src/app/tree

**Comment by mrmscmike** [comment]
Thank you very much!
