### ISSUE TITLE
support solid shadow item

### ISSUE THREAD

**Issue by soncomqiq** [reppners/ngx-drag-drop#149]
I would like to raise an issue I encountered while using the ngx-drag-drop library. In my project, I've incorporated ngx-drag-drop, but I faced an issue where an item got positioned behind a notification box. When attempting to drag the item, its shadow overlapped with the notification box.

I replicated this issue on [the official ngx-drag-drop page](https://reppners.github.io/ngx-drag-drop/), and the problem occurred there as well. You can observe the problem in the following images:

![image](https://github.com/reppners/ngx-drag-drop/assets/21175358/a1f6a1e6-5c49-467e-8c58-dda9cd12cf92)

In order to address this issue, I propose that the developers make the dragged item's shadow appear solid, similar to the behavior seen in [Angular Material](https://material.angular.io/cdk/drag-drop/overview):

![image](https://github.com/reppners/ngx-drag-drop/assets/21175358/947c8db7-0c31-4413-a48f-0ac5ffb0c085)

This enhancement would greatly improve the user experience.

Thank you for your attention to this matter.

**Comment by ChristofFritz** [comment]
We rely heavy on the browser rendering the drag image. So this is not possible. The angular cdk handles drag and drop very different. They manually adjust the position of a real element via javascript.
