### ISSUE TITLE
Angular 16 - Standalone directives

### ISSUE THREAD

**Issue by puranjayjain** [reppners/ngx-drag-drop#151]
**Is your feature request related to a problem? Please describe.**
Angular 16 now supports standalone directives which can be used inside hostdirectives or used separately.

**Describe the solution you'd like**
This way of declaring and using them reduces the amount of code we need for download for each component.

**Describe alternatives you've considered**
We right now do have an alternative of using the dndmodule inside the component directy.

**Comment by ChristofFritz** [comment]
You'll be pleased to hear that the directives are now standalone. The DndModule still exports them to not break existing applications that use the DndModule

**Comment by puranjayjain** [comment]
Thanks a lot @ChristofFritz
