### ISSUE TITLE
Using v16 with Angular 11

### ISSUE THREAD

**Issue by bureaug** [reppners/ngx-drag-drop#154]
Installed the package v16. Added `DndModule` to `app.module`, but auto-import wouldn't find it. Imported it manually. When compiling with `npm start` get the following message:

```
Error: ./node_modules/ngx-drag-drop/fesm2015/ngx-drag-drop.mjs 1050:12-24
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)
```
and many more of that kind.

Searching Stackoverflow and other sources pointed me to webpack.config, which I don't have. If I need to add .mjs extensions to some config, I am not sure to which one. Thanks in advance!

**Versions**
Nodejs 16.20.2
npm 8.19.4
Typescript 3.5.2

**Comment by bureaug** [comment]
I have now tried installing 2.0.0 and 13.0.0 - nothing worked yet.

**Comment by ChristofFritz** [comment]
Angular 11 is not supported. Sorry.
