### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by Roozenboom** [reppners/ngx-drag-drop#170]
We want are migrating to Angular 18 and when we install the package ngx-drag-drop throws a warning for unmet peer dependency

warning " > ngx-drag-drop@17.0.0" has incorrect peer dependency "@angular/common@^17.0.0".
warning " > ngx-drag-drop@17.0.0" has incorrect peer dependency "@angular/core@^17.0.0".

Are there any plans to support Angular 18?

**Comment by Ookamini95** [comment]
at the moment I'm using it with --force on 18 and it's working mostly fine (no particular bug found).

**Comment by MoInMaRvZ** [comment]
I opened a pull request for update to angular 18, https://github.com/reppners/ngx-drag-drop/pull/172

**Comment by henkkelder** [comment]
@MoInMaRvZ 
Is there a way I could use your branch?

**Comment by screambeard** [comment]
Is there anyway I or other can help with this?

**Comment by egorkel-altexsoft** [comment]
> @MoInMaRvZ Is there a way I could use your branch?

You can use github URL instead of version
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#github-urls

**Comment by henkkelder** [comment]
> > @MoInMaRvZ Is there a way I could use your branch?
> 
> You can use github URL instead of version https://docs.npmjs.com/cli/v10/configuring-npm/package-json#github-urls

I think that only works of the repos contains a build version of the package. I don't think is this is the case here.

**Comment by egorkel-altexsoft** [comment]
Yep, it does not build the lib. Unlucky

**Comment by Roozenboom** [comment]
#172 is merged. version 18 is released. https://github.com/reppners/ngx-drag-drop/releases/tag/v18.0.0
