### ISSUE TITLE
Angular 6 upgrade

### ISSUE THREAD

**Issue by mtraynham** [reppners/ngx-drag-drop#21]
I gave it an initial pass, but I'm not entirely clear on how the angular-cli works or how it's set up with this project.

**Comment by reppners** [comment]
I've yet to look at the details of how angular cli v6 does it, but it should be just some "rewiring" of how it works at the moment. Angular cli's library support is based on ng-packagr which is already used now to make the library build for this project.

Relevant angular cli docs concerning libraries https://github.com/angular/angular-cli/wiki/stories-create-library

I've not yet tested if the currently released library build works in v6 as is. Will setup a stackblitz to see if it works.

**Comment by reppners** [comment]
Setup a issue template StackBlitz, seems like the library works fine with angular v6.

https://stackblitz.com/edit/ngx-drag-drop-issue-template

**Comment by reppners** [comment]
Jumped straight to ng v7
