### ISSUE TITLE
Drop down does not scroll but can drop up and scroll

### ISSUE THREAD

**Issue by 1456118242** [reppners/ngx-drag-drop#22]
![drop](https://user-images.githubusercontent.com/18241022/40213787-e88b89e8-5a89-11e8-9e0f-b055f06b6752.gif)

Please see my picture
What do you think is the problem?

**Comment by reppners** [comment]
This library does not implement any mechanism to help scrolling while dragging.
Each browser behaves differently, maybe even operating system dependent. 

Did you try to deactivate the transition on dragover?

**Comment by 1456118242** [comment]
Not the issue of transition on dragover. I am very depressed when dragging up can scroll but dragging down can't scroll. I saw your demo no such problem. Thank you very much

**Comment by 1456118242** [comment]
When dragging down can not respond to this dom scroll event

**Comment by 1456118242** [comment]
Thank you @reppners

**Comment by reppners** [comment]
So was your issue solved somehow?

**Comment by 1456118242** [comment]
Yes

**Comment by chetankh23** [comment]
@1456118242 How you managed to get the scroll working ?
