### ISSUE TITLE
set dndType on drop in a restricted div.

### ISSUE THREAD

**Issue by selva98** [reppners/ngx-drag-drop#23]
I m following a typed demo where i am having multiple value in dropzone ie array and when i drop a li in this div its setting the first one in dropzone attribute array but i would like set my self for dndType.
I have searched but i didn't get what i m trying, can you help me how i can achieve this.

**Comment by reppners** [comment]
I'm not entirely clear I can follow your question and use case description.

Please provide a minimal example of your use case based on this https://stackblitz.com/edit/ngx-drag-drop-issue-template

**Comment by selva98** [comment]
Thanks for a soon reply , 
i m new bee , 
can we manually set the dndType on Drop event,
current it was setting last value of array ng-reflect-dnd-dropzone in ul into li  ng-reflect-dnd-type attribute but i need to set it manually , 
for example in dropzone  i ve 5ad6ff051de3a249f832a4c5, 5ad70b1d1de3a223a89e97e6               5af02bd21de3a20a34fede43
and when i drop element having dndType 5ad70b1d1de3a223a89e97e6 , it was setting dndType to 
5af02bd21de3a20a34fede43 but i need dndType to be 5af02bd21de3a20a34fede43

**Comment by selva98** [comment]
Thanks Stefan,The problem was solved , i m checking the element which is already in the dom instead of drop element, this problem raised mainly because of data's in the element are almost same so i unexpectedly checking the element in the second position instead of dropped on which is in first position in list.

**Comment by reppners** [comment]
Good 👍 Closing as solved 😀
