### ISSUE TITLE
Placeholder is not removed in IE11 (+error)

### ISSUE THREAD

**Issue by gpaucot** [reppners/ngx-drag-drop#26]
**Describe the bug**
Placeholder is not removed at startup
In the console : 
TypeError: Object doesn't support property or method 'remove'
at DndDropzoneDirective.prototype.ngAfterViewInit (eval code:496:13)
...

**To Reproduce**
https://stackblitz.com/edit/ngx-drag-drop-issue-template-mquokq
(it is the template without any modification)

1. Open the console on IE11

**Expected behavior**
Compatibility with IE11

**LIB version**
1.0.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 11

**Comment by gpaucot** [comment]
PR: #27

**Comment by nischi** [comment]
I need that as well. Please acceppt the PR. Thanks

**Comment by reppners** [comment]
Thanks for the issue and follow up PR 👍 

Please give me some time to get to this. I'm busy because I moved recently and was offline for a couple of days.

**Comment by reppners** [comment]
Released as of v2.0.0-rc.1

**Comment by nischi** [comment]
Thanks a lot
