### ISSUE TITLE
recursive data model

### ISSUE THREAD

**Issue by gnututor** [reppners/ngx-drag-drop#28]
the library get a "TypeError: Converting circular structure to JSON" when you handle a recursive data model

https://stackblitz.com/edit/ngx-drag-drop-issue-template-cx9zgp?file=src/app/app.component.html

**Comment by reppners** [comment]
I see where you're coming from but I'm not planning to add support for recursive data structures as drag data. There is almost always a better alternative than heavy serialization in drag/drop:

To handle recursive data structures, build a service/data store that will enable you to reference your drag data by an id string/number and just set the id as your drag data. In your drop handlers get the data by the id and operate on it as you need.

If you need further help or an example implementation let me know.

**Comment by gnututor** [comment]
thank you for reply!!

Yes, it will be useful to have your example implementation. 

For now, my solution was to build a data structure where data are logically in that structure but physically in a map. 
The map is queried by the structure (via service) to retrieving data.

**Comment by reppners** [comment]
Basically your solution is the same to what I would've suggested showcased. Closing as solved/answered.
