### ISSUE TITLE
setDragImage() Issue with Edge

### ISSUE THREAD

**Issue by JaronrH** [reppners/ngx-drag-drop#29]
Edge throws an error when using Drag-Drop with a handle due to setDragImage() not being a valid function.  Fix (for now) was to comment out the following in ngx-drag-drop.es5.js/ngx-drag-drop.js  so that it isn't called:

        // set custom dragimage if present
        // set dragimage if drag is started from dndHandle
        if (typeof this.dndDragImageElementRef !== "undefined"
            || typeof event._dndUsingHandle !== "undefined") {
            setDragImage(event, this.dragImage, this.dndDragImageOffsetFunction);
        }

**Comment by reppners** [comment]
Thanks for reporting! Do you know of any workarounds or polyfills for `setDragImage()` to make it work on Edge / IE?

**Comment by nischi** [comment]
Okay do not really work with strict mode :(

**Comment by nischi** [comment]
so "fixed" my problem. I do not care about IE11 setDragImage function so i have done a polyfill like this:

`
if ('function' !== typeof DataTransfer.prototype.setDragImage) {
  DataTransfer.prototype.setDragImage = function(image, offsetX, offsetY) { };
}
`

**Comment by reppners** [comment]
Closing this one as by now Edge uses Chromium.
