### ISSUE TITLE
When the number of items is very large, about 300, dragging is very slow

### ISSUE THREAD

**Issue by 1456118242** [reppners/ngx-drag-drop#30]
Please see the gif
![22](https://user-images.githubusercontent.com/18241022/42065500-c534e688-7b6d-11e8-921e-deb580bd18d3.gif)

**Comment by 1456118242** [comment]
@reppners

**Comment by reppners** [comment]
I'll try to reproduce, meanwhile please try the `next` version, installable by `npm install ngx-drag-drop@next --save` which contains some performance optimizations that might help your case.

**Comment by krixerx** [comment]
@next  version looks very good, tnx!
