### ISSUE TITLE
Drop not working in angular 6 environment

### ISSUE THREAD

**Issue by tis78** [reppners/ngx-drag-drop#38]
Drag and drop not working with angular 6, Please help me out.
Thanks in advance.

**Comment by reppners** [comment]
I need more details. Which exact angular version? Which version of ngx-drag-drop? What exactly does not work? Can you provide a stackblitz showing the failure?

**Comment by tis78** [comment]
Sorry, my mistake it was 5.2.0,  
This is my package.json, Please have a look -

    "dependencies": {
        "@angular/animations": "^5.2.0",
        "@angular/common": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0",
        "@angular/forms": "^5.2.0",
        "@angular/http": "^5.2.0",
        "@angular/platform-browser": "^5.2.0",
        "@angular/platform-browser-dynamic": "^5.2.0",
        "@angular/router": "^5.2.0",
        "bootstrap": "^3.3.7",
        "chart.js": "^2.7.2",
        "core-js": "^2.4.1",
        "dragula": "^3.7.2",
        "file-saver": "^1.3.8",
        "fullcalendar": "3.5.1",
        "iframe-resizer": "^3.6.1",
        "intl": "1.2.5",
        "jquery": "3.2.1",
        "jquery-ui-dist": "^1.12.1",
        "moment": "^2.22.2",
        "nanoscroller": "^0.8.7",
        "ng2-bootstrap": "^1.6.3",
        "ngx-bootstrap": "^2.0.4",
        "primeng": "^5.2.5",
        "quill": "1.1.8",
        "rxjs": "^5.5.6",
        "save": "^2.3.2",
        "web-animations-js": "2.3.1",
        "zone.js": "^0.8.19"
    },
    "devDependencies": {
        "@angular/cli": "~1.7.4",
        "@angular/compiler-cli": "^5.2.0",
        "@angular/language-service": "^5.2.0",
        "@types/iframe-resizer": "^3.5.6",
        "@types/jasmine": "~2.8.3",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "^4.0.1",
        "jasmine-core": "~2.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "^2.0.5",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "^5.4.0",
        "ts-node": "~4.1.0",
        "tslint": "~5.9.1",
        "typescript": "~2.5.3"
    }

**Comment by reppners** [comment]
You're also specifying dragula as dependency - I'm no dragula expert but could there be some conflict with native drag and drop when dragula is active?

**Comment by reppners** [comment]
This issue still lacks substantial information to be able to reproduce. If you can provide more information or a reproduction I'm happy to reopen and help. Until then closed as non actionable.
