### ISSUE TITLE
RXJS 6

### ISSUE THREAD

**Issue by bastienmoulia** [reppners/ngx-drag-drop#39]
**Describe the bug**
Got an incompatible peer dependencies error for rxjs when i try to upgrade to the last version of angular (6.1.7) with `ng update --all`.

>Package "ngx-drag-drop" has an incompatible peer dependency to "rxjs" (requires "^5.1.0", would install "6.3.2").

**Comment by reppners** [comment]
Thx for reporting. I'll look into it.

**Comment by reppners** [comment]
I assume its fixed. Let me know if its not and I'll reopen 👍

**Comment by bastienmoulia** [comment]
It works!
