### ISSUE TITLE
last npm version mismatch last repository release

### ISSUE THREAD

**Issue by GeoAstronaute** [reppners/ngx-drag-drop#4]
Hi @reppners,

First of all, thank you for your work. This repo was exactly what I needed. 

I have however an issue using your library in an electron application with webpack and angular. I notice that the last version on npm is aplha0 and not your last release on this repo: v1.0.0-rc.0. I don't know if my issue is related with this mismatch of release version : 

![ngx-drag-drop-npm-screenshot](https://user-images.githubusercontent.com/14280160/29919327-2a0fa9c0-8e49-11e7-8315-97d8c895d3e4.JPG)

Indeed I have to change the "main: index.js" to "main: ngx-drag-drop.umd.js" to get your package working, if not, I get this error : 
`C:\Users\Jmarc\Documents\Programmation\materia-designer-angular4\src\node_modules\ngx-drag-drop\index.js:1 Uncaught SyntaxError: Unexpected token import`.

When I use "ngx-drag-drop.umd.js" instead of "index.js", everything works as expected.

Any help will be greatly appreciated.

**Comment by reppners** [comment]
Which version did you install? 1.0.0-rc.0 is also available on npm. Npm just won't update the web page for some reason I don't know. Maybe it's just working for version changes that are not pre-releases.

I'm using it with angular-cli/webpack and its working fine. Can you post the content of your local download of the library's "index.js"?

**Comment by GeoAstronaute** [comment]
In my package.json I have : 
  "ngx-drag-drop": "next"

Here is the content of "index.js" in my local download : 
`import { ContentChild, Directive, ElementRef, EventEmitter, HostBinding, HostListener, Input, NgModule, Output, Renderer2 } from '@angular/core';
import { CommonModule } from '@angular/common';

var DROP_EFFECTS = (["move", "copy", "link"]);
var CUSTOM_MIME_TYPE = "application/x-dnd";
var JSON_MIME_TYPE = "application/json";
var MSIE_MIME_TYPE = "Text";
/**
 * @param {?} mimeType
 * @return {?}
 */
function mimeTypeIsCustom(mimeType) {
    return mimeType.substr(0, CUSTOM_MIME_TYPE.length) === CUSTOM_MIME_TYPE;
}
/**
 * @param {?} event
 * @return {?}
 */
function getWellKnownMimeType(event) {
    var /** @type {?} */ types = event.dataTransfer.types;
    // IE 9 workaround.
    if (!types) {
        return MSIE_MIME_TYPE;
    }
    for (var /** @type {?} */ i = 0; i < types.length; i++) {
        if (types[i] === MSIE_MIME_TYPE
            || types[i] === JSON_MIME_TYPE
            || mimeTypeIsCustom(types[i])) {
            return types[i];
        }
    }
    return null;
}
/**
 * @param {?} event
 * @param {?} data
 * @param {?} effectAllowed
 * @return {?}
 */
function setDragData(event, data, effectAllowed) {
    // Internet Explorer and Microsoft Edge don't support custom mime types, see design doc:
    // https://github.com/marceljuenemann/angular-drag-and-drop-lists/wiki/Data-Transfer-Design
    var /** @type {?} */ mimeType = CUSTOM_MIME_TYPE + (data.type ? ("-" + data.type) : "");
    var /** @type {?} */ dataString = JSON.stringify(data);
    try {
        event.dataTransfer.setData(mimeType, dataString);
    }
    catch (e) {
        //   Setting a custom MIME type did not work, we are probably in IE or Edge.
        try {
            event.dataTransfer.setData(JSON_MIME_TYPE, dataString);
        }
        catch (e) {
            //   We are in Internet Explorer and can only use the Text MIME type. Also note that IE
            //   does not allow changing the cursor in the dragover event, therefore we have to choose
            //   the one we want to display now by setting effectAllowed.
            var /** @type {?} */ effectsAllowed = filterEffects(DROP_EFFECTS, effectAllowed);
            event.dataTransfer.effectAllowed = effectsAllowed[0];
            event.dataTransfer.setData(MSIE_MIME_TYPE, dataString);
        }
    }
}
/**
 * @param {?} event
 * @param {?} dragIsExternal
 * @return {?}
 */
function getDropData(event, dragIsExternal) {
    // check if the mime type is well known
    var /** @type {?} */ mimeType = getWellKnownMimeType(event);
    // drag did not originate from [dndDraggable]
    if (dragIsExternal === true) {
        if (mimeType !== null
            && mimeTypeIsCustom(mimeType)) {
            // the type of content is well known and safe to handle
            return JSON.parse(event.dataTransfer.getData(mimeType));
        }
        // the contained data is unknown, let user handle it
        return {};
    }
    // the type of content is well known and safe to handle
    return JSON.parse(event.dataTransfer.getData(mimeType));
}
/**
 * @param {?} effects
 * @param {?} allowed
 * @return {?}
 */
function filterEffects(effects, allowed) {
    if (allowed === "all") {
        return effects;
    }
    return effects.filter(function (effect) {
        return allowed.toLowerCase().indexOf(effect) !== -1;
    });
}
/**
 * @param {?} parentElement
 * @param {?} childElement
 * @return {?}
 */
function getDirectChildElement(parentElement, childElement) {
    var /** @type {?} */ directChild = childElement;
    while (directChild.parentNode !== parentElement) {
        // reached root node without finding given parent
        if (!directChild.parentNode) {
            return null;
        }
        directChild = directChild.parentNode;
    }
    return (directChild);
}
/**
 * @param {?} event
 * @param {?} element
 * @param {?} horizontal
 * @return {?}
 */
function shouldPositionPlaceholderBeforeElement(event, element, horizontal) {
    var /** @type {?} */ bounds = element.getBoundingClientRect();
    // If the pointer is in the upper half of the list item element,
    // we position the placeholder before the list item, otherwise after it.
    if (horizontal) {
        return (event.clientX < bounds.left + bounds.width / 2);
    }
    return (event.clientY < bounds.top + bounds.height / 2);
}
/**
 * @param {?} event
 * @param {?} dragImage
 * @return {?}
 */
function calculateDragImageOffset(event, dragImage) {
    var /** @type {?} */ dragImageComputedStyle = window.getComputedStyle(dragImage);
    var /** @type {?} */ paddingTop = parseFloat(dragImageComputedStyle.paddingTop) || 0;
    var /** @type {?} */ paddingLeft = parseFloat(dragImageComputedStyle.paddingLeft) || 0;
    var /** @type {?} */ borderTop = parseFloat(dragImageComputedStyle.borderTopWidth) || 0;
    var /** @type {?} */ borderLeft = parseFloat(dragImageComputedStyle.borderLeftWidth) || 0;
    return {
        x: event.offsetX + paddingLeft + borderLeft,
        y: event.offsetY + paddingTop + borderTop
    };
}
/**
 * @param {?} event
 * @param {?} dragImage
 * @param {?} offsetFunction
 * @return {?}
 */
function setDragImage(event, dragImage, offsetFunction) {
    var /** @type {?} */ offset = offsetFunction(event, dragImage) || { x: 0, y: 0 };
    ((event.dataTransfer)).setDragImage(dragImage, offset.x, offset.y);
}

var DndHandleDirective = (function () {
    /**
     * @param {?} elementRef
     */
    function DndHandleDirective(elementRef) {
        this.elementRef = elementRef;
        this.draggable = true;
    }
    /**
     * @param {?} event
     * @return {?}
     */
    DndHandleDirective.prototype.onDragEvent = function (event) {
        event._dndHandle = (this.elementRef.nativeElement);
    };
    return DndHandleDirective;
}());
DndHandleDirective.decorators = [
    { type: Directive, args: [{
                selector: "[dndHandle]"
            },] },
];
/**
 * @nocollapse
 */
DndHandleDirective.ctorParameters = function () { return [
    { type: ElementRef, },
]; };
DndHandleDirective.propDecorators = {
    'draggable': [{ type: HostBinding, args: ["attr.draggable",] },],
    'onDragEvent': [{ type: HostListener, args: ["dragstart", ["$event"],] }, { type: HostListener, args: ["dragend", ["$event"],] },],
};

var _dndState = {
    isDragging: false,
    dropEffect: "none",
    effectAllowed: "all",
    type: undefined
};
/**
 * @param {?} event
 * @param {?} effectAllowed
 * @param {?=} type
 * @return {?}
 */
function startDrag(event, effectAllowed, type) {
    _dndState.isDragging = true;
    _dndState.dropEffect = "none";
    _dndState.effectAllowed = effectAllowed;
    _dndState.type = type;
    event.dataTransfer.effectAllowed = effectAllowed;
}
/**
 * @return {?}
 */
function endDrag() {
    _dndState.isDragging = false;
    _dndState.dropEffect = undefined;
    _dndState.effectAllowed = undefined;
    _dndState.type = undefined;
}
/**
 * @param {?} event
 * @param {?} dropEffect
 * @return {?}
 */
function setDropEffect(event, dropEffect) {
    if (_dndState.isDragging === true) {
        _dndState.dropEffect = dropEffect;
    }
    event.dataTransfer.dropEffect = dropEffect;
}
/**
 * @param {?} event
 * @param {?=} effectAllowed
 * @return {?}
 */
function getDropEffect(event, effectAllowed) {
    var /** @type {?} */ effects = DROP_EFFECTS;
    effects = filterEffects(effects, /** @type {?} */ (event.dataTransfer.effectAllowed));
    if (_dndState.isDragging === true) {
        effects = filterEffects(effects, _dndState.effectAllowed);
    }
    if (effectAllowed) {
        effects = filterEffects(effects, effectAllowed);
    }
    // MacOS automatically filters dataTransfer.effectAllowed depending on the modifier keys,
    // therefore the following modifier keys will only affect other operating systems.
    if (effects.length === 0) {
        return "none";
    }
    if (event.ctrlKey && effects.indexOf("copy") !== -1) {
        return "copy";
    }
    if (event.altKey && effects.indexOf("link") !== -1) {
        return "link";
    }
    return (effects[0]);
}
/**
 * @param {?} event
 * @return {?}
 */
function getDndType(event) {
    if (_dndState.isDragging === true) {
        return _dndState.type;
    }
    var /** @type {?} */ mimeType = getWellKnownMimeType(event);
    if (mimeType === null) {
        return undefined;
    }
    if (mimeType === MSIE_MIME_TYPE
        || mimeType === JSON_MIME_TYPE) {
        return undefined;
    }
    return mimeType.substr(CUSTOM_MIME_TYPE.length + 1) || undefined;
}
/**
 * @return {?}
 */
function isExternalDrag() {
    return _dndState.isDragging === false;
}
var dndState = (_dndState);

var DndElementRefDirective = (function () {
    /**
     * @param {?} elementRef
     */
    function DndElementRefDirective(elementRef) {
        this.elementRef = elementRef;
    }
    return DndElementRefDirective;
}());
DndElementRefDirective.decorators = [
    { type: Directive, args: [{
                selector: "[dndPlaceholderRef], [dndDragImageRef]"
            },] },
];
/**
 * @nocollapse
 */
DndElementRefDirective.ctorParameters = function () { return [
    { type: ElementRef, },
]; };

var DndDraggableDirective = (function () {
    /**
     * @param {?} elementRef
     * @param {?} renderer
     */
    function DndDraggableDirective(elementRef, renderer) {
        this.elementRef = elementRef;
        this.renderer = renderer;
        this.dndEffectAllowed = "copy";
        this.dndDraggingClass = "dndDragging";
        this.dndDraggingSourceClass = "dndDraggingSource";
        this.dndDraggableDisabledClass = "dndDraggableDisabled";
        this.dndDragImageOffsetFunction = calculateDragImageOffset;
        this.dndStart = new EventEmitter();
        this.dndEnd = new EventEmitter();
        this.dndMoved = new EventEmitter();
        this.dndCopied = new EventEmitter();
        this.dndLinked = new EventEmitter();
        this.dndCanceled = new EventEmitter();
        this.draggable = true;
    }
    Object.defineProperty(DndDraggableDirective.prototype, "dndDisableIf", {
        /**
         * @param {?} value
         * @return {?}
         */
        set: function (value) {
            this.draggable = !value;
            if (this.draggable) {
                this.renderer.removeClass(this.elementRef.nativeElement, this.dndDraggableDisabledClass);
            }
            else {
                this.renderer.addClass(this.elementRef.nativeElement, this.dndDraggableDisabledClass);
            }
        },
        enumerable: true,
        configurable: true
    });
    /**
     * @return {?}
     */
    DndDraggableDirective.prototype.ngAfterContentInit = function () {
        // evaluate custom drag image existence
        if (typeof this.dndDragImageRef !== "undefined") {
            this.dragImage = (this.dndDragImageRef.elementRef.nativeElement);
        }
        else {
            this.dragImage = this.elementRef.nativeElement;
        }
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDraggableDirective.prototype.onDragStart = function (event) {
        var _this = this;
        if (this.draggable === false) {
            return false;
        }
        // check if there is dnd handle and if the dnd handle was used to start the drag
        if (typeof this.dndHandle !== "undefined"
            && typeof event._dndHandle === "undefined") {
            return false;
        }
        // initialize global state
        startDrag(event, this.dndEffectAllowed);
        setDragData(event, { data: this.dndDraggable, type: this.dndType }, dndState.effectAllowed);
        // add dragging source css class on first drag event
        var /** @type {?} */ unregister = this.renderer.listen(this.elementRef.nativeElement, "drag", function () {
            _this.renderer.addClass(_this.elementRef.nativeElement, _this.dndDraggingSourceClass);
            unregister();
        });
        // set dragging css class prior to setDragImage so styles are applied before
        this.renderer.addClass(this.dragImage, this.dndDraggingClass);
        // set custom dragimage if present
        // set dragimage if drag is started from dndHandle
        if (typeof this.dndDragImageRef !== "undefined"
            || typeof event._dndHandle !== "undefined") {
            setDragImage(event, this.dragImage, this.dndDragImageOffsetFunction);
        }
        this.dndStart.emit(event);
        event.stopPropagation();
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDraggableDirective.prototype.onDragEnd = function (event) {
        var _this = this;
        // get drop effect from custom stored state as its not reliable across browsers
        var /** @type {?} */ dropEffect = dndState.dropEffect;
        var /** @type {?} */ dropEffectEmitter;
        switch (dropEffect) {
            case "copy":
                dropEffectEmitter = this.dndCopied;
                break;
            case "link":
                dropEffectEmitter = this.dndLinked;
                break;
            case "move":
                dropEffectEmitter = this.dndMoved;
                break;
            default:
                dropEffectEmitter = this.dndCanceled;
                break;
        }
        dropEffectEmitter.emit(event);
        this.dndEnd.emit(event);
        // reset global state
        endDrag();
        this.renderer.removeClass(this.dragImage, this.dndDraggingClass);
        // IE9 special hammering
        window.setTimeout(function () {
            _this.renderer.removeClass(_this.elementRef.nativeElement, _this.dndDraggingSourceClass);
        }, 0);
        event.stopPropagation();
    };
    return DndDraggableDirective;
}());
DndDraggableDirective.decorators = [
    { type: Directive, args: [{
                selector: "[dndDraggable]"
            },] },
];
/**
 * @nocollapse
 */
DndDraggableDirective.ctorParameters = function () { return [
    { type: ElementRef, },
    { type: Renderer2, },
]; };
DndDraggableDirective.propDecorators = {
    'dndDraggable': [{ type: Input },],
    'dndEffectAllowed': [{ type: Input },],
    'dndType': [{ type: Input },],
    'dndDraggingClass': [{ type: Input },],
    'dndDraggingSourceClass': [{ type: Input },],
    'dndDraggableDisabledClass': [{ type: Input },],
    'dndDragImageOffsetFunction': [{ type: Input },],
    'dndStart': [{ type: Output },],
    'dndEnd': [{ type: Output },],
    'dndMoved': [{ type: Output },],
    'dndCopied': [{ type: Output },],
    'dndLinked': [{ type: Output },],
    'dndCanceled': [{ type: Output },],
    'draggable': [{ type: HostBinding, args: ["attr.draggable",] },],
    'dndHandle': [{ type: ContentChild, args: [DndHandleDirective,] },],
    'dndDragImageRef': [{ type: ContentChild, args: [DndElementRefDirective,] },],
    'dndDisableIf': [{ type: Input },],
    'onDragStart': [{ type: HostListener, args: ["dragstart", ["$event"],] },],
    'onDragEnd': [{ type: HostListener, args: ["dragend", ["$event"],] },],
};

var DndDropzoneDirective = (function () {
    /**
     * @param {?} elementRef
     * @param {?} renderer
     */
    function DndDropzoneDirective(elementRef, renderer) {
        this.elementRef = elementRef;
        this.renderer = renderer;
        this.dndAllowExternal = false;
        this.dndHorizontal = false;
        this.dndDragoverClass = "dndDragover";
        this.dndDropzoneDisabledClass = "dndDropzoneDisabled";
        this.dndDragover = new EventEmitter();
        this.dndDrop = new EventEmitter();
        this.placeholder = null;
        this.disabled = false;
    }
    Object.defineProperty(DndDropzoneDirective.prototype, "dndDisableIf", {
        /**
         * @param {?} value
         * @return {?}
         */
        set: function (value) {
            this.disabled = !!value;
            if (this.disabled) {
                this.renderer.addClass(this.elementRef.nativeElement, this.dndDropzoneDisabledClass);
            }
            else {
                this.renderer.removeClass(this.elementRef.nativeElement, this.dndDropzoneDisabledClass);
            }
        },
        enumerable: true,
        configurable: true
    });
    /**
     * @return {?}
     */
    DndDropzoneDirective.prototype.ngAfterContentInit = function () {
        if (typeof this.dndPlaceholderRef !== "undefined") {
            this.placeholder = (this.dndPlaceholderRef.elementRef.nativeElement);
            this.placeholder.remove();
        }
    };
    /**
     * @param {?=} type
     * @return {?}
     */
    DndDropzoneDirective.prototype.isDropAllowed = function (type) {
        // dropzone is disabled -> deny it
        if (this.disabled === true) {
            return false;
        }
        // if drag did not start from our directive
        // and external drag sources are not allowed -> deny it
        if (isExternalDrag() === true
            && this.dndAllowExternal === false) {
            return false;
        }
        // no filtering by types -> allow it
        if (!this.dndDropzone) {
            return true;
        }
        // no type set -> allow it
        if (!type) {
            return true;
        }
        // if dropzone contains type -> allow it
        return this.dndDropzone.indexOf(type) !== -1;
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDropzoneDirective.prototype.checkAndUpdatePlaceholderPosition = function (event) {
        if (this.placeholder === null) {
            return;
        }
        // make sure the placeholder is in the DOM
        if (this.placeholder.parentNode !== this.elementRef.nativeElement) {
            this.renderer.appendChild(this.elementRef.nativeElement, this.placeholder);
        }
        // update the position if the event originates from a child element of the dropzone
        var /** @type {?} */ directChild = getDirectChildElement(this.elementRef.nativeElement, /** @type {?} */ (event.target));
        // early exit if no direct child or direct child is placeholder
        if (directChild === null
            || directChild === this.placeholder) {
            return;
        }
        var /** @type {?} */ positionPlaceholderBeforeDirectChild = shouldPositionPlaceholderBeforeElement(event, directChild, this.dndHorizontal);
        if (positionPlaceholderBeforeDirectChild) {
            // do insert before only if necessary
            if (directChild.previousSibling !== this.placeholder) {
                this.renderer.insertBefore(this.elementRef.nativeElement, this.placeholder, directChild);
            }
        }
        else {
            // do insert after only if necessary
            if (directChild.nextSibling !== this.placeholder) {
                this.renderer.insertBefore(this.elementRef.nativeElement, this.placeholder, directChild.nextSibling);
            }
        }
    };
    /**
     * @return {?}
     */
    DndDropzoneDirective.prototype.getPlaceholderIndex = function () {
        if (this.placeholder === null) {
            return undefined;
        }
        var /** @type {?} */ element = (this.elementRef.nativeElement);
        return Array.prototype.indexOf.call(element.children, this.placeholder);
    };
    /**
     * @return {?}
     */
    DndDropzoneDirective.prototype.cleanupDragoverState = function () {
        this.renderer.removeClass(this.elementRef.nativeElement, this.dndDragoverClass);
        if (this.placeholder !== null) {
            this.placeholder.remove();
        }
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDropzoneDirective.prototype.onDragEnter = function (event) {
        // check if another dropzone is activated
        if (event._dndDropzoneActive === true) {
            this.cleanupDragoverState();
            return;
        }
        // set as active if the target element is inside this dropzone
        if (typeof event._dndDropzoneActive === "undefined") {
            var /** @type {?} */ newTarget = document.elementFromPoint(event.clientX, event.clientY);
            if (this.elementRef.nativeElement.contains(newTarget)) {
                event._dndDropzoneActive = true;
            }
        }
        // check if this drag event is allowed to drop on this dropzone
        var /** @type {?} */ type = getDndType(event);
        if (this.isDropAllowed(type) === false) {
            return;
        }
        // allow the dragenter
        event.preventDefault();
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDropzoneDirective.prototype.onDragOver = function (event) {
        // check if this drag event is allowed to drop on this dropzone
        var /** @type {?} */ type = getDndType(event);
        if (this.isDropAllowed(type) === false) {
            return;
        }
        this.checkAndUpdatePlaceholderPosition(event);
        var /** @type {?} */ dropEffect = getDropEffect(event, this.dndEffectAllowed);
        if (dropEffect === "none") {
            this.cleanupDragoverState();
            return;
        }
        // allow the dragover
        event.preventDefault();
        // set the drop effect
        setDropEffect(event, dropEffect);
        this.dndDragover.emit(event);
        this.renderer.addClass(this.elementRef.nativeElement, this.dndDragoverClass);
        event.stopPropagation();
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDropzoneDirective.prototype.onDrop = function (event) {
        try {
            // check if this drag event is allowed to drop on this dropzone
            var /** @type {?} */ type = getDndType(event);
            if (this.isDropAllowed(type) === false) {
                return;
            }
            var /** @type {?} */ data = getDropData(event, isExternalDrag());
            if (this.isDropAllowed(data.type) === false) {
                return;
            }
            // signal custom drop handling
            event.preventDefault();
            var /** @type {?} */ dropEffect = getDropEffect(event);
            setDropEffect(event, dropEffect);
            if (dropEffect === "none") {
                return;
            }
            var /** @type {?} */ dropIndex = this.getPlaceholderIndex();
            this.dndDrop.emit({
                event: event,
                dropEffect: dropEffect,
                isExternal: isExternalDrag(),
                data: data.data,
                index: dropIndex
            });
            event.stopPropagation();
        }
        finally {
            this.cleanupDragoverState();
        }
    };
    /**
     * @param {?} event
     * @return {?}
     */
    DndDropzoneDirective.prototype.onDragLeave = function (event) {
        // check if still inside this dropzone and not yet handled by another dropzone
        if (typeof event._dndDropzoneActive === "undefined") {
            var /** @type {?} */ newTarget = document.elementFromPoint(event.clientX, event.clientY);
            if (this.elementRef.nativeElement.contains(newTarget)) {
                event._dndDropzoneActive = true;
                return;
            }
        }
        this.cleanupDragoverState();
        // cleanup drop effect when leaving dropzone
        setDropEffect(event, "none");
    };
    return DndDropzoneDirective;
}());
DndDropzoneDirective.decorators = [
    { type: Directive, args: [{
                selector: "[dndDropzone]"
            },] },
];
/**
 * @nocollapse
 */
DndDropzoneDirective.ctorParameters = function () { return [
    { type: ElementRef, },
    { type: Renderer2, },
]; };
DndDropzoneDirective.propDecorators = {
    'dndDropzone': [{ type: Input },],
    'dndEffectAllowed': [{ type: Input },],
    'dndAllowExternal': [{ type: Input },],
    'dndHorizontal': [{ type: Input },],
    'dndDragoverClass': [{ type: Input },],
    'dndDropzoneDisabledClass': [{ type: Input },],
    'dndDragover': [{ type: Output },],
    'dndDrop': [{ type: Output },],
    'dndPlaceholderRef': [{ type: ContentChild, args: [DndElementRefDirective,] },],
    'dndDisableIf': [{ type: Input },],
    'onDragEnter': [{ type: HostListener, args: ["dragenter", ["$event"],] },],
    'onDragOver': [{ type: HostListener, args: ["dragover", ["$event"],] },],
    'onDrop': [{ type: HostListener, args: ["drop", ["$event"],] },],
    'onDragLeave': [{ type: HostListener, args: ["dragleave", ["$event"],] },],
};

var DndModule = (function () {
    function DndModule() {
    }
    return DndModule;
}());
DndModule.decorators = [
    { type: NgModule, args: [{
                imports: [
                    CommonModule
                ],
                declarations: [
                    DndDraggableDirective,
                    DndDropzoneDirective,
                    DndHandleDirective,
                    DndElementRefDirective
                ],
                exports: [
                    DndDraggableDirective,
                    DndDropzoneDirective,
                    DndHandleDirective,
                    DndElementRefDirective
                ]
            },] },
];
/**
 * @nocollapse
 */
DndModule.ctorParameters = function () { return []; };

export { DndModule, DndDraggableDirective, DndDropzoneDirective, DndHandleDirective, DndElementRefDirective };
`

We use @angular-cli 1.3.0 with an ejected webpack config to use "electron-renderer" as "target" and we have "target: es5" in our tsconfig.json.

**Comment by reppners** [comment]
So I think the issue is that it is not transpiled correctly for the node environment.

Can you try something like proposed here?

https://stackoverflow.com/a/45023796/3370601
https://stackoverflow.com/a/45239961/3370601

**Comment by GeoAstronaute** [comment]
Thanks a lot! 

I fix my issue with the first link you provided. 
I modified the webpack.config.js file as follows:
`"target": "electron-renderer",
  "externals": [nodeExternals({
    whitelist: [
      /^ngx-drag-drop/
    ]
  })]`

It works great now!

**Comment by reppners** [comment]
Nice! Don't hesitate to report any bugs you're encountering :-)
