### ISSUE TITLE
DndDropEvent.index may be -1

### ISSUE THREAD

**Issue by sebek64** [reppners/ngx-drag-drop#40]
**Describe the bug**
When drag and drop is done rapidly, DndDropEvent.index is -1.

**To Reproduce**
https://ngx-drag-drop-issue-template-hja8ga.stackblitz.io

Try to rapidly drag an element. Sometimes, console shows

```
dropped {
  "event": {
    "isTrusted": true
  },
  "dropEffect": "move",
  "isExternal": false,
  "data": "myDragData",
  "index": -1
}
```

**Expected behavior**
We should never get index === -1 (or if so, it should be clearly documented).

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Browser Chrome
 - Version 69.0.3497.92 (Official Build) (64-bit)

**Additional context**
The issue is present in 2.0.0-rc.2 and probably also in 1.0.4.

**Comment by reppners** [comment]
Thanks for the detailed report! Looking into it 🤔

**Comment by reppners** [comment]
So.. how rapid do I need to perform the drag and drop for this to happen? I wasn't able to reproduce on my machine though I'm quite sure this can happen if inserting the placeholder takes too long for whatever reason.

There's two options:
1. If the placeholder is not inserted do not propagate the drop event.
2. Propagate with index === -1 and document that it can happen.

I think I'd prefer option 1 but I'm open to suggestions and feedback.

**Comment by reppners** [comment]
Not yet released. I'll ping in this issue when its contained in next release.
