### ISSUE TITLE
dndType not working on angular6

### ISSUE THREAD

**Issue by liranbi92** [reppners/ngx-drag-drop#47]
Hey, dndType isnt working on angular 6.

I tried to set it on the div like this:
`<div class="cd"
         [dndDraggable]="draggable.data"
         [dndEffectAllowed]="draggable.effectAllowed"
         (dndStart)="onDragStart($event,'section')"
         [dndType]="section"
>{{ name }}</div>`

and on drop tried to receive it but i always get "undefined".

**Comment by reppners** [comment]
dndType is for limiting where items can be dropped. If you set it on a draggable you can set the same value on a dropzone and it will only accept items with matching type. 

Also in your example you bind the variable section to dndType. Is the variable defined in your component or was your intention to set the dndType to string value 'section'?

**Comment by mksmtn** [comment]
Working fine on angular 6

**Comment by reppners** [comment]
@liranbi92 I think you misunderstood the purpose of `dndType`. You can't receive it on drop as it is not transported in the drop event. If you need the information in the drop event it should be part of the data that you transport with `dndDraggable`, in your case `draggable.data`.

If you still need further advice feel free to reply here and I'll reopen the issue. Until then I'll close as answered.

**Comment by reppners** [comment]
Wait a minute.. I've misread my own stuff 😅 .. I'll try to reproduce.

**Comment by reppners** [comment]
Confirmed!

**Comment by reppners** [comment]
Well.. it works if you're using the latest version. Had misconfigured my stackblitz which used v1.0.3 but it works in v1.1.0

What version are you using?

**Comment by liranbi92** [comment]
Yes its work now!
thanks!

**Comment by reppners** [comment]
👍
