### ISSUE TITLE
Support angular 7

### ISSUE THREAD

**Issue by sebek64** [reppners/ngx-drag-drop#49]
**Describe the bug**
Angular 7 is currently not formally supported. A warning is produced:

warning " > ngx-drag-drop@2.0.0-rc.3" has incorrect peer dependency "@angular/core@^4.0.0 || ^5.0.0 || ^6.0.0".

**Comment by dev-ps23** [comment]
Angular 7 has CDK's drag drop module integrated. Maybe use ngx-drag-drop as wrapper for it in angular 7.   BTW thanks for this wonderful package <3 . :-)

**Comment by alecrt** [comment]
Any news on Angular 7 version?

**Comment by VigneshVaidyanathan** [comment]
I am using Angular 7 and I am not facing any issues or warning. It works as in the example but I am trying without the Angular Material.

**Comment by reppners** [comment]
Updated build and demo to use angular 7. It always worked without issues but I guess this makes it kind of official 🤔 😄
