### ISSUE TITLE
Demo Lists "go to source" returning 404

### ISSUE THREAD

**Issue by Crocsx** [reppners/ngx-drag-drop#51]
**Describe the bug**
When you click "go to source" in the Demo, it doesn't bring you to the correct page.

**To Reproduce**
=> GO TO : https://reppners.github.io/ngx-drag-drop/
=> GO TO : lists
=> CLICK : Go to Source

**Current behavior**
redirect to : https://github.com/reppners/ngx-drag-drop/tree/master/demo/app/lists
**Expected behavior**
redirect to : https://github.com/reppners/ngx-drag-drop/tree/master/demo/app/list

**Comment by reppners** [comment]
Thanks for reporting 👍  I fixed it with the latest commit.
