### ISSUE TITLE
How to set position of dragged image

### ISSUE THREAD

**Issue by nvernooy** [reppners/ngx-drag-drop#56]
I'm using the `dndHandle` element in the far right of my `dndDraggable` element, then when I start dragging the dragged image jumps so that the left side is under the cursor, not the right side that was originally clicked. This can be disorienting to be user, is there a way to fix the position of the dragged image?

![image](https://user-images.githubusercontent.com/5332516/51172987-2929c680-18bd-11e9-9f8c-b35bd8800c15.png)

![image](https://user-images.githubusercontent.com/5332516/51173101-62623680-18bd-11e9-93c3-2e2f30dca153.png)

**Comment by reppners** [comment]
Hi, sorry for the long delay. There is a way to customize the drag image offset.

The dndDraggable has an input `dndDragImageOffsetFunction` which expects a function with signature `( event:DragEvent, dragImage:Element ) => { x:number, y:number };`

This is the default implementation
```TypeScript
export function calculateDragImageOffset( event:DragEvent, dragImage:Element ):{ x:number, y:number } {

  const dragImageComputedStyle = window.getComputedStyle( dragImage );
  const paddingTop = parseFloat( dragImageComputedStyle.paddingTop ) || 0;
  const paddingLeft = parseFloat( dragImageComputedStyle.paddingLeft ) || 0;
  const borderTop = parseFloat( dragImageComputedStyle.borderTopWidth ) || 0;
  const borderLeft = parseFloat( dragImageComputedStyle.borderLeftWidth ) || 0;

  return {
    x: event.offsetX + paddingLeft + borderLeft,
    y: event.offsetY + paddingTop + borderTop
  };
}
```

I'll incorporate an example in the demo in a future release.

**Comment by reppners** [comment]
I've just updated the simple demo with a very naive approach that should get you started. Hope it helps :)

**Comment by nvernooy** [comment]
Thanks thats great!
