### ISSUE TITLE
Cannot find name 'DndDropEvent'.

### ISSUE THREAD

**Issue by netdjw** [reppners/ngx-drag-drop#58]
I just copied the example code into my component and at this code:

```
  onDrop(event: DndDropEvent) {
    console.log('dropped', JSON.stringify(event, null, 2));
  }
```
I get this error:

`error TS2304: Cannot find name 'DndDropEvent'.`

**Comment by reppners** [comment]
Have you added the import for the type?

`import { DndDropEvent } from 'ngx-drag-drop';`

**Comment by netdjw** [comment]
Yes. Of course.

**Comment by reppners** [comment]
Must be an issue with your project setup, I can't reproduce this wether in stackblitz nor in a local project. If you are able to share your project setup (tsconfig.json, package.json) that might help figure out what the issue is.

**Comment by netdjw** [comment]
Ach, I missed the import:

`import { DndDropEvent } from 'ngx-drag-drop';`

Sorry for wasting your time.
