### ISSUE TITLE
Firefox - autoscroll not work

### ISSUE THREAD

**Issue by DenisDremkov** [reppners/ngx-drag-drop#64]
**Describe the bug**
 - when we move mouse to the bottom or to the top of container (container with directive  dndDropzone) and will stop cursor we will not get expected behavior - auto scroll to the top (to the bottom). We have to move mouse that auto scroll will work - https://www.loom.com/share/a29e9124f9b440a28e77b61aa1b780f7

**To Reproduce**
just reproduce it like in the video 

**Expected behavior**
it have to work like in Chrome - https://www.loom.com/share/a71fce9dab31483aab8e66a09ad6e25e

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - Browser [Firefox]
 - Version [Firefox 66]

Could you answer - is it possible to do?

**Comment by reppners** [comment]
Thanks for reporting. Couldn't reproduce in Firefox 66.0.5 on macOS. Will try on Ubuntu tomorrow.

**Comment by reppners** [comment]
Latest versions of Firefox did autoscroll fine for me. Also this is more or less browser territory. I've tested Firefox, Chrome and Safari. Autoscroll is flaky, making it quite hard to polyfill in a general purpose way.
