### ISSUE TITLE
Issue in Safari

### ISSUE THREAD

**Issue by DenisDremkov** [reppners/ngx-drag-drop#65]
**Describe the bug**
Have to work autoscroll in Safari if we drag element to the top or to the bottom of scroll container? How you can see in the video screencast (below) I tried to have autoscroll but it not work. I have added polyfill like you described in the instruction. But I can't understand autoscroll have to work or not? But for touch devices it work perfectly. 

**To Reproduce**
https://www.loom.com/share/e1eb3ebf3f87401dbd4d42f3db68e04c

**Desktop (please complete the following information):**
 - OS: [ios]
 - Browser [safari]
 - Version [12+]

**Smartphone (please complete the following information):**
 - Device: [iMac]

**And Thanks for library! After usage some libraries (CDK...), I guess your solution is the best.

**Comment by reppners** [comment]
The polyfill for mobile drag drop has this functionality implemented but desktop browsers are not all behaving the same here. Some browsers do autoscroll, others don't. 

I don't have any plans to polyfill desktop autoscroll.

But it should be possible to implement yourself, you can take inspiration from the implementation at https://github.com/timruffles/mobile-drag-drop/blob/master/src/scroll-behaviour.ts

**Comment by reppners** [comment]
Closing as out of scope and implementation can be done on application level.
