### ISSUE TITLE
Cleanup on destroy

### ISSUE THREAD

**Issue by andreroggeri** [reppners/ngx-drag-drop#67]
**Describe the bug**
If the directive is destroyed before the dragend event, it stays on a invalid state.
For example, anything can be dragged to a dropzone because the current state is still dragging.
I believe that calling the `endDrag` method on destroy should fix this issue
**To Reproduce**
If possible please provide a StackBlitz based on this template
https://stackblitz.com/edit/ngx-drag-drop-destroy-cleanup?file=src/app/app.component.html

1. Try to drag the title of the page to the basket
2. Drag a element from the market to the basket
3. Repeat step 1 and check the console.

**Expected behavior**
It should not allow to drag elements that are not draggable (Only in case of dndAllowExternal=true) and no error should occur on console
**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 75

**Comment by reppners** [comment]
Welcome and thanks for the thorough bug report!

Good catch 👍 fixed with [2.0.0-rc.7](https://github.com/reppners/ngx-drag-drop/releases/tag/v2.0.0-rc.7)

**Comment by andreroggeri** [comment]
Great! 😁
Any chance of this being ported to 1.x.x versions?

I can't use alpha/beta/RC packages on my company 😔

**Comment by reppners** [comment]
Sure, v1.1.1 it is 😃

**Comment by reppners** [comment]
But you can use v2.0.0 as well because it's out now as stable.
