### ISSUE TITLE
Upgrading to angular 8

### ISSUE THREAD

**Issue by hijazikaram** [reppners/ngx-drag-drop#68]
After upgrading my codebase to Angular 8, started getting an error "Property 'querySelector' does not exist on type 'EventTarget". Is it because the module yet doesnt support Angular 8?

`const dragImage = event.srcElement.querySelector('.nav-item.marker');`

**Comment by reppners** [comment]
Hi and thanks for reporting. I have not yet tried it with Angular v8 but the error message suggests it's either a change in Angular or TypeScript causing this.

**Comment by hijazikaram** [comment]
> Hi and thanks for reporting. I have not yet tried it with Angular v8 but the error message suggests it's either a change in Angular or TypeScript causing this.

Ya, im using the latest version of angular with version typescript of 3.4.5

**Comment by hijazikaram** [comment]
@reppners Any news on this?

**Comment by reppners** [comment]
@hijazikaram Had no time for open source work because of day job and family. I'll try to look into it at the weekend.

**Comment by hijazikaram** [comment]
Thank you for very much!

**Comment by muuvmuuv** [comment]
Should be renamed to NG9 ^^

**Comment by dhrn** [comment]
+1

**Comment by dhrn** [comment]
soon we can rename to NG10  :smile:

**Comment by reppners** [comment]
Will be jumping directly to v13
