### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by srudhish** [reppners/ngx-drag-drop#69]
does ngx drag and drop work only with angular material? because i cannot apply styles on it. am using boostrap 4 with angular 7. Give me any complete example to implement ngx drag and drop.
I appreciate your efforts and Thank you in advance.

**Comment by reppners** [comment]
This lib is agnostic of the UI library used. Please provide a more specific description of the problem and if possible provide a stackblitz that reproduces the problem.

**Comment by srudhish** [comment]
I was trying to apply styles to the element which animates when dragging, but I couldn't. I have seen that you where using material ui to implement this plugin. please take a look into the image I have uploaded here. in that, the red lined part is which i need to customize.

![image](https://user-images.githubusercontent.com/50352467/60379936-14e81900-9a5a-11e9-8c66-ee942fe24715.png)

**Comment by reppners** [comment]
I don't think animations work well with HTML5 drag and drop since the browsers are taking a snapshot of the element to use as a drag image when drag starts. This is in no way related to material ui but a general HTML5 drag and drop limitation.

**Comment by reppners** [comment]
If HTML5 drag and drop issues are a limitation please give https://material.angular.io/cdk/drag-drop/overview a spin!
