### ISSUE TITLE
Drag and drop in touch screen is not working

### ISSUE THREAD

**Issue by unnatishah96** [reppners/ngx-drag-drop#7]
I am not using angular2-material. Is there any way to use this drag and drop in touch screen devices ?

**Comment by reppners** [comment]
For touch support use the [polyfill](https://github.com/timruffles/ios-html5-drag-drop-shim) mentioned in the [README](https://github.com/reppners/ngx-drag-drop).

Angular Material is just used for the demo, there is no dependency on it for the library to work.

**Comment by kikkiraj** [comment]
i am using Angular 8 and tried to follow Touch support in ReadMe, but it says js file.. so wondering which js file you are referring to.. need help if you can provide more clarity on this.
