### ISSUE TITLE
Wrong offset when using dndHandle with polyfill on mobile

### ISSUE THREAD

**Issue by nekkon** [reppners/ngx-drag-drop#70]
Hello thanks for making this library. Has been useful so far. I have an issue when dragging on a mobile device. 

I am trying to use the dndHandle while using the polyfill for mobile devices. When dragging dndHandle the element that appears as I am dragging does not appear at the right position. It is 50% on the left of its width from the handle. The handle is on the left, so the dragging element appears half. 

The above functionality works fine on desktop. Any suggestions on how to solve this? Thanks in advance. I have attached a screenshot. Feel free to ask for any info that might help things out.

![drag bug](https://user-images.githubusercontent.com/8094269/60356880-110cb600-99ca-11e9-9dcc-41f323940b95.png)

**Comment by reppners** [comment]
Welcome and sorry for the long delay.

This is most likely an issue with specific css involved in the elements that are dragged. There are most likely ways to work around those styling issues but I need a reproduction to help you with that. I've used `dndHandle` with the polyfill for mobile devices and was able to overcome any layout issues. Unfortunately theres no one size fits all way of handling all the possible css variations that can be solved at the library/polyfill level.
