### ISSUE TITLE
Q: Can this be used to implement a list based dnd?

### ISSUE THREAD

**Issue by CarstenLeue** [reppners/ngx-drag-drop#71]
Can this library be used to implement drag and drop for lists? 
The library seems to imply that the drop target covers some real estate. In case of a list however the drop target would be in between two list items. How could this be represented?

**Comment by reppners** [comment]
Welcome and sorry for the long delay.

Do the various demos which also feature lists answer your question?
https://reppners.github.io/ngx-drag-drop/
