### ISSUE TITLE
Can't bind to 'dndDraggable' 

### ISSUE THREAD

**Issue by jitan16** [reppners/ngx-drag-drop#72]
Can't bind to 'dndDraggable' since it isn't a known property of 'div'. ("
<div class="draggable" [ERROR ->][dndDraggable]="draggable.data" [dndEffectAllowed]="draggable.effectAllowed"
  [dndDisableIf]="dragga")

I'm getting this error. How can I fix this error? Thank you

**Comment by reppners** [comment]
Welcome :)

Make sure to have the `DndModule` imported so it is available in your component where you want to use the `dndDraggable` directive.

Example
```ts
import { DndModule } from 'ngx-drag-drop';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    DndModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { 
}
```

**Comment by jitan16** [comment]
Wow, it works! Big thanks @reppners.
