### ISSUE TITLE
dndDragoverClass works inconsistently

### ISSUE THREAD

**Issue by JanvanCasteren** [reppners/ngx-drag-drop#76]
In notice that the dragover class is not always removed when the mouse is moving out of the dropzone. This behaviour is inconsistent. When I repeat dragging over the dropzone sometimes the class is correctly removed and sometimes not. I don't really see a pattern.

Could this be a bug, or must it be something that incorrect in my code?

![dragover2](https://user-images.githubusercontent.com/388176/65179868-f4799a80-da5b-11e9-97aa-2c3dbb95aeec.gif)

**Comment by Langstra** [comment]
What did you do to fix this issue?
