### ISSUE TITLE
Drag and drop get stuck on Safari browser

### ISSUE THREAD

**Issue by samir-satpute** [reppners/ngx-drag-drop#77]
When we drag and drop on safari browser using 'dndHandle' drag and drop getting stuck.
for more details refer to the following screen record.

https://www.dropbox.com/s/nov5u3swokos7ny/Screen%20Recording%202019-10-15%20at%2010.53.03%20PM.mov?dl=0

**Comment by reppners** [comment]
Sorry for the quite large delay. The video is not available anymore. If you're still experiencing the issue I'm happy to reopen!
