### ISSUE TITLE
Dragging a <tr> above the second column in a table causes jittering with a placeholder

### ISSUE THREAD

**Issue by vaindil** [reppners/ngx-drag-drop#82]
**Describe the bug**
If a `<tbody>` is a drop zone, individual `<tr>`s within it are draggable, and a placeholder is being used, then dragging the `<tr>` over any column other than the first in the table causes massive jittering when hovering over the top half of the cell.

**To Reproduce**
[StackBlitz is here.](https://stackblitz.com/edit/ngx-drag-drop-issue-template-dml1jf?file=src/app/app.component.html) This was borrowed from #2, I just added an extra `<td>` to each row.

1. Start dragging any row
2. Drag the row over the first column of any row, see that the placeholder is smooth.
3. Drag the row over the top half of a cell in the second column of any row, see that the placeholder is continually added and removed.

**Expected behavior**
The placeholder should behave smoothly like it does in the first column.

**Screenshots**
![ngx-dnd](https://user-images.githubusercontent.com/771134/75827887-9544e380-5d78-11ea-8e78-a1f2463d7833.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 74, Chrome 80

**Additional context**
This is happening because of [this line](https://github.com/reppners/ngx-drag-drop/blob/master/src/dnd-dropzone.directive.ts#L260) -- `document.getElementFromPoint()` is returning the `<table>` element instead of the `<td>` or anything inside it. I don't know if this is a bug in Firefox/Chrome or if the library can do something about it.

**Comment by reppners** [comment]
Those kinds of issues are really hard to get right on the library level and as suggested by @matheusAle it almost always can be solved by application specific DOM structure/styling.
