### ISSUE TITLE
Browser scroll not working while dragging

### ISSUE THREAD

**Issue by jigneshInd** [reppners/ngx-drag-drop#83]
**Describe the bug**

I am using four horizontal box to drag and drop images to each other box, but while selecting image from last box and wants to put it on first box which is not  on viewport, and need to scroll that time browser scroll not working while element selected for dragging.

**To Reproduce**
You can create four similar box with same height and try to drag and drop item to each other, you will see you can't able to drag from last box to first one.

**Comment by 4i-helpynet** [comment]
Same problem here. If the drop zone isn't in view, and you have to scroll, the drop event isn't work.

If you zoom out to view the full form, then it's working.

**Comment by reppners** [comment]
This is more or less browser territory and since not all browsers are likely to behave the same in regards of automatic scrolling when dragging an item near the viewport border this may be hard to get right. It can be done but I'm unsure if this should be part of this module.
