### ISSUE TITLE
Question - how to get data where I dropped data?

### ISSUE THREAD

**Issue by profeciak** [reppners/ngx-drag-drop#89]
**Is your feature request related to a problem? Please describe.**
I'm moving a task from one phase to another. I'm not sure how can I achieve the phase data to which I dropped my task. I specially need the id of the new phase.
Inside the DndDropEvent I have all object that I move, but I'm lacking data of object to which I move

**Comment by pavittar95** [comment]
@reppners I got the same issue.

**Comment by mohamad-daresay** [comment]
according to [documents](https://github.com/marceljuenemann/angular-drag-and-drop-lists/wiki/Data-Transfer-Design) 
`event.dataTransfer?.getData('application/x-dnd')`

**Comment by esmaeilpour** [comment]
according to documents, you can have access to data like this
event.dataTransfer?.getData('application/x-dnd')

**Comment by reppners** [comment]
The context of your dropzone should carry this information. I'd imagine your dropzones are the containers for the phases and your drop handler basically should have this information implicitly or you need to provide it in your component code. If the dropzones are dynamically rendered with a ngFor then the model used for the ngFor needs to carry this information and from there it can be easily passed to the drop handler invocation. If you need a code example I can come up with something.
