### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by mzarnitsa** [reppners/ngx-drag-drop#9]
Guys, tried to use your control. Works great in all desktop browsers I tried. Howerver, on iOS Safari, both iPhone and iPad drag simply doesn't start at all. It all just goes to scroll.

Tried your examples at https://reppners.github.io/ngx-drag-drop/, also a mess. Doesn't draw correctly, drag doesn't work.

Any plans on addressing that?

**Comment by reppners** [comment]
Thanks for trying out the library and providing feedback!

Touch support is provided by the [polyfill](https://github.com/timruffles/ios-html5-drag-drop-shim) mentioned in the README.
However I forgot to add the [workaround](https://github.com/timruffles/ios-html5-drag-drop-shim/issues/77) needed for Safari that enables to prevent scroll when dragging.
Will push a fix for this in a minute.

The demos are not tuned for mobile yet. PR's are welcome to improve the demos 😄

**Comment by mzarnitsa** [comment]
Thanks, I'll give polyfills a try. Missed that in the readme.

**Comment by reppners** [comment]
I'm going to make that more prominent - you're not the first one to ask on how touch support is established.

**Comment by reppners** [comment]
Readme updated :)
