### ISSUE TITLE
Unable to add dnddrop event listener

### ISSUE THREAD

**Issue by SwapnilGopale** [reppners/ngx-drag-drop#92]
**Describe the bug**

**To Reproduce**
If possible please provide a StackBlitz based on this template
https://stackblitz.com/edit/ngx-drag-drop-issue-template

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu 16.8]
 - Browser [chrome, safari,firefox]
 - Version [Latest]

**Smartphone (please complete the following information):**

**Additional context**
Hi,

I am new to angular and I have tried this library but there is one issue that I am not able to add dnddrop event listener from my Ts file for the dynamically created dropzone div.

`value.addEventListener("drop", function( event ) {
                        // prevent default action (open as link for some elements)
                        event.preventDefault();
                        self.onDrop(self.data[index-1].id);

                    });`
here value is dynamically created dropzone.

This did not work for me

**Comment by reppners** [comment]
Adding event listeners manually is an anti-pattern. The directives provide events that should make it unnecessary to add classic event listeners. If you need more guidance let me know.
